import type { Metadata } from "next";
import { Inter, Quicksand, Rubik } from "next/font/google";
import "./globals.css";
import "katex/dist/katex.min.css";
import { twMerge } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"] });
const qs = Quicksand({ subsets: ["latin"] });
const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={twMerge(rubik.className, "overflow-x-hidden")}>
        {children}
      </body>
    </html>
  );
}
